@startuml
skinparam class {
    BackgroundColor<<focus>> PaleGreen
    BorderColor<<focus>> Black
    BackgroundColor<<sys>> Tomato
    BorderColor<<sys>> Black
}
class UserAgent <<focus>>
interface UserAgentCommon
interface AgentPersistentActor
interface BasePersistentActor
abstract class PersistentActor <<sys>>
interface EventPersistenceEncryption
interface CoreActorExtended
interface CoreActor
abstract class Actor <<sys>>
interface EntityIdentifier
interface HasActorTimers
abstract class Timers <<sys>>
interface HasActorResponseTimeout
interface DeleteMsgHandler
interface HasTransformationRegistry
interface LegacyTransformationRegistry
abstract class Stash <<sys>>
class DefaultPersistenceEncryption
interface HasAppConfig
interface UserAgentCommonStateUpdateImpl
interface AgentStateUpdateInterface
interface MsgAndDeliveryHandler
interface AgentMsgHandler
interface AgentCommon
interface AgentIdentity
interface HasAgentWallet
interface HasWallet
interface HasSetRoute
interface ResourceUsageCommon
interface ProtocolEngineExceptionHandler
interface AgentIncomingMsgHandler
interface AgentOutgoingMsgHandler
interface SendOutgoingMsg
interface HasAgentActivity
interface ShardRegionCommon
interface ShardRegionNames
interface HasShardRegionNames
interface MsgTraceProvider
class MsgRespTimeTracker
class MsgProgressTracker
interface HasAsyncReqContext
interface AgentStateCleanupHelper
interface HasLogger
interface ShardRegionFromActorContext
interface MsgStoreAPI
interface LEGACY_connectingSignalHandler
interface UserAgentStateUpdateImpl
interface MsgNotifierForUserAgent
interface MsgNotifierForUserAgentCommon
interface MsgNotifierForStoredMsgs
interface MsgNotifier
interface PushNotifMsgBuilder
interface AgentSnapshotter
interface AgentStateInterface
class State
interface SnapshotterExt
abstract class Snapshotter <<sys>>
class UserAgentPairwise <<focus>>
interface UserAgentPairwiseStateUpdateImpl
interface AgentMsgSender
interface HasGeneralCache
interface UsesConfigs
abstract class PairwiseConnState <<sys>>
interface MsgDeliveryResultHandler
interface HasAgentMsgTransformer
interface MsgNotifierForUserAgentPairwise
interface FailedMsgRetrier
class AgencyAgent <<focus>>
interface AgencyAgentCommon
interface AgencyAgentStateUpdateImpl
interface AgencyPackedMsgHandler
class AgencyAgentPairwise <<focus>>
interface AgencyAgentPairwiseStateUpdateImpl

UserAgent -up-|> UserAgentCommon
UserAgent -* UserAgentStateUpdateImpl
UserAgent -down-* HasAgentActivity
UserAgent --* MsgNotifierForUserAgent
UserAgent -down-* AgentSnapshotter
UserAgentCommon -up-|> AgentPersistentActor
UserAgentCommon -* UserAgentCommonStateUpdateImpl
UserAgentCommon -* MsgAndDeliveryHandler
UserAgentCommon --* AgentMsgHandler
UserAgentCommon -down-* ShardRegionFromActorContext
UserAgentCommon -* MsgStoreAPI
UserAgentCommon --* LEGACY_connectingSignalHandler
AgentPersistentActor -up-|> BasePersistentActor
AgentPersistentActor -* DefaultPersistenceEncryption
AgentPersistentActor --* HasAppConfig
BasePersistentActor -up-|> PersistentActor
BasePersistentActor -* EventPersistenceEncryption
BasePersistentActor --* CoreActorExtended
BasePersistentActor -* HasActorResponseTimeout
BasePersistentActor -* DeleteMsgHandler
BasePersistentActor --* HasTransformationRegistry
BasePersistentActor -down-* Stash
CoreActorExtended -up-|> CoreActor
CoreActorExtended -* HasActorTimers
CoreActor -up-|> Actor
CoreActor -* EntityIdentifier
HasActorTimers -up-|> Timers
HasTransformationRegistry -up-|> LegacyTransformationRegistry
UserAgentCommonStateUpdateImpl -up-|> AgentStateUpdateInterface
AgentMsgHandler -up-|> AgentCommon
AgentMsgHandler -down-* ProtocolEngineExceptionHandler
AgentMsgHandler --* AgentIncomingMsgHandler
AgentMsgHandler --* AgentOutgoingMsgHandler
AgentMsgHandler -down-* MsgTraceProvider
AgentMsgHandler -* AgentStateCleanupHelper
AgentMsgHandler -down-* HasLogger
AgentCommon -up-|> AgentStateUpdateInterface
AgentCommon -* AgentIdentity
AgentCommon --* HasAgentWallet
AgentCommon -* HasSetRoute
AgentCommon --* ResourceUsageCommon
HasAgentWallet -up-|> HasWallet
AgentOutgoingMsgHandler -up-|> SendOutgoingMsg
AgentOutgoingMsgHandler -down-* AgentIdentity
AgentOutgoingMsgHandler -down-* HasAgentActivity
HasAgentActivity -up-|> ShardRegionCommon
ShardRegionCommon -up-|> ShardRegionNames
ShardRegionNames -up-|> HasShardRegionNames
MsgTraceProvider -up-|> MsgRespTimeTracker
MsgTraceProvider --* MsgProgressTracker
MsgTraceProvider -* HasAsyncReqContext
ShardRegionFromActorContext -up-|> ShardRegionCommon
UserAgentStateUpdateImpl -up-|> UserAgentCommonStateUpdateImpl
MsgNotifierForUserAgent -up-|> MsgNotifierForUserAgentCommon
MsgNotifierForUserAgentCommon -up-|> MsgNotifierForStoredMsgs
MsgNotifierForStoredMsgs -up-|> MsgNotifier
MsgNotifierForStoredMsgs -down-* PushNotifMsgBuilder
PushNotifMsgBuilder -up-|> HasAppConfig
AgentSnapshotter --* AgentStateInterface
AgentSnapshotter -up-|> SnapshotterExt
AgentStateInterface -up-|> State
SnapshotterExt -up-|> Snapshotter
UserAgentPairwise -up-|> UserAgentCommon
UserAgentPairwise -* UserAgentPairwiseStateUpdateImpl
UserAgentPairwise --* AgentMsgSender
UserAgentPairwise --* UsesConfigs
UserAgentPairwise -down-* PairwiseConnState
UserAgentPairwise -down-* MsgDeliveryResultHandler
UserAgentPairwise --* MsgNotifierForUserAgentPairwise
UserAgentPairwise -* FailedMsgRetrier
UserAgentPairwise -down-* AgentSnapshotter
UserAgentPairwiseStateUpdateImpl -up-|> UserAgentCommonStateUpdateImpl
AgentMsgSender -up-|> HasGeneralCache
AgentMsgSender -down-* HasLogger
UsesConfigs -up-|> HasAppConfig
MsgDeliveryResultHandler -up-|> HasAgentMsgTransformer
MsgNotifierForUserAgentPairwise -up-|> MsgNotifierForUserAgentCommon
AgencyAgent -up-|> AgencyAgentCommon
AgencyAgent -* AgencyAgentStateUpdateImpl
AgencyAgent -* AgencyPackedMsgHandler
AgencyAgent -down-* AgentSnapshotter
AgencyAgentCommon -up-|> AgentPersistentActor
AgencyAgentCommon --* AgentMsgHandler
AgencyAgentCommon -down-* ShardRegionFromActorContext
AgencyAgentCommon --* MsgNotifier
AgencyAgentCommon -* LEGACY_connectingSignalHandler
AgencyAgentStateUpdateImpl -up-|> AgentStateUpdateInterface
AgencyPackedMsgHandler -up-|> ResourceUsageCommon
AgencyAgentPairwise -up-|> AgencyAgentCommon
AgencyAgentPairwise -* AgencyAgentPairwiseStateUpdateImpl
AgencyAgentPairwise -down-* PairwiseConnState
AgencyAgentPairwise -down-* AgentSnapshotter
AgencyAgentPairwiseStateUpdateImpl -up-|> AgentStateUpdateInterface

@enduml
