@startuml

title Calls in the "fwd" Flow

autonumber 1
note over PackedMsgEndpointHandler #ffffff: handleAgentMsgReq( ) -- Packed msg\narrives.
PackedMsgEndpointHandler --> PackedMsgEndpointHandler
note over PackedMsgEndpointHandler #ffffff: handleAgentMsgReqForOctetStreamContentType( )\n-- Detect binary content.
PackedMsgEndpointHandler -> AgencyPackedMsgHandler
note over AgencyPackedMsgHandler #ffffff: processPackedMsg( ) -- Decrypt and check\nmessage type.
AgencyPackedMsgHandler --> AgencyPackedMsgHandler
note over AgencyPackedMsgHandler #ffffff: handleFwdMsg( ) -- Called after seeing\n"Forward" in plaintext.
AgencyPackedMsgHandler -> AgentMsgRouter
note over AgentMsgRouter #ffffff: executeCmd( ) -- trigger routing for\npacked messages.
AgentMsgRouter --> AgentMsgRouter
note over AgentMsgRouter #ffffff: routePackedMsg( ) -- Find route to\nrelevant actor, send inner msg.
AgentMsgRouter -> AgentIncomingMsgHandler
note over AgentIncomingMsgHandler #ffffff: handlePackedMsg( ) -- Receive and\ndecrypt.
AgentIncomingMsgHandler --> AgentIncomingMsgHandler
note over AgentIncomingMsgHandler #ffffff: handleAgentMsgWrapper( ) -- Re-examine\nafter decrypt.

group 100: edge
autonumber 101
AgentIncomingMsgHandler --> AgentIncomingMsgHandler
note over AgentIncomingMsgHandler #ffffff: handleDecryptedMsg( ) -- store outgoing\nmsg.
AgentIncomingMsgHandler -> AgentMsgHandler
note over AgentMsgHandler #ffffff: sendStoredMsgToEdge( ) -- Queue msg for\ndelivery to edge.
end

@enduml
