@startuml

title Calls in the "legacy" Flow

autonumber 1
note over PackedMsgEndpointHandler #ffffff: handleAgentMsgReq( ) -- Packed msg\narrives.
PackedMsgEndpointHandler --> PackedMsgEndpointHandler
note over PackedMsgEndpointHandler #ffffff: handleAgentMsgReqForOctetStreamContentType( )\n-- Detect binary content.
PackedMsgEndpointHandler --> PackedMsgEndpointHandler
note over PackedMsgEndpointHandler #ffffff: processPackedMsg( ) -- Decrypt and check\nmessage type.
PackedMsgEndpointHandler -> AgencyPackedMsgHandler
note over AgencyPackedMsgHandler #ffffff: handleFwdMsg( ) -- Called after seeing\n"Forward" in plaintext.
AgencyPackedMsgHandler -> AgentMsgRouter
note over AgentMsgRouter #ffffff: routePackedMsg( ) -- Find route to\nrelevant actor, send inner msg.
AgentMsgRouter -> AgentMsgProcessor
note over AgentMsgProcessor #ffffff: handleProcessPackedMsg( ) -- Receive and\ndecrypt.

@enduml
