@startuml
skinparam class {
    BackgroundColor<<focus>> PaleGreen
    BorderColor<<focus>> Black
    BackgroundColor<<sys>> Tomato
    BorderColor<<sys>> Black
}
class UserAgent <<focus>>
class UserAgentPairwise <<focus>>
class AgencyAgent <<focus>>
interface AgencyAgentCommon
interface AgentPersistentActor
interface BasePersistentActor
abstract class PersistentActor <<sys>>
interface EventPersistenceEncryption
interface CoreActorExtended
interface CoreActor
abstract class Actor <<sys>>
class EntityIdentifier
abstract class ActorLogging <<sys>>
interface HasActorTimers
abstract class Timers <<sys>>
interface HasActorResponseTimeout
interface DeleteMsgHandler
interface HasTransformationRegistry
interface LegacyTransformationRegistry
interface PersistentEntityIdentifier
abstract class Stash <<sys>>
interface HasExecutionContextProvider
class DefaultPersistenceEncryption
interface HasAppConfig
interface AgentMsgHandler
interface AgentCommon
interface AgentStateUpdateInterface
interface AgentIdentity
interface HasAgentWallet
interface HasWallet
interface HasSetRoute
interface HasMsgProgressTracker
interface HasSingletonParentProxy
interface ResourceUsageCommon
interface ProtocolEngineExceptionHandler
interface AgentIncomingMsgHandler
interface AgentOutgoingMsgHandler
interface SendOutgoingMsg
interface HasOutgoingMsgSender
interface HasAgentActivity
interface ShardRegionCommon
interface ShardRegionNames
interface HasShardRegionNames
class MsgRespTimeTracker
interface AgentStateCleanupHelper
interface HasLogger
interface ShardRegionFromActorContext
interface MsgNotifier
interface LEGACY_connectingSignalHandler
interface AgencyAgentStateUpdateImpl
interface AgencyPackedMsgHandler
interface AgentSnapshotter
interface AgentStateInterface
interface State
interface SnapshotterExt
abstract class Snapshotter <<sys>>
class AgencyAgentPairwise <<focus>>
interface AgencyAgentPairwiseStateUpdateImpl
abstract class PairwiseConnState <<sys>>

AgencyAgent -up-|> AgencyAgentCommon
AgencyAgent -* AgencyAgentStateUpdateImpl
AgencyAgent -* AgencyPackedMsgHandler
AgencyAgent -down-* AgentSnapshotter
AgencyAgentCommon -up-|> AgentPersistentActor
AgencyAgentCommon --* AgentMsgHandler
AgencyAgentCommon -down-* ShardRegionFromActorContext
AgencyAgentCommon --* MsgNotifier
AgencyAgentCommon -* LEGACY_connectingSignalHandler
AgentPersistentActor -up-|> BasePersistentActor
AgentPersistentActor -* DefaultPersistenceEncryption
AgentPersistentActor --* HasAppConfig
BasePersistentActor -up-|> PersistentActor
BasePersistentActor -* EventPersistenceEncryption
BasePersistentActor --* CoreActorExtended
BasePersistentActor -* HasActorResponseTimeout
BasePersistentActor -* DeleteMsgHandler
BasePersistentActor --* HasTransformationRegistry
BasePersistentActor -* PersistentEntityIdentifier
BasePersistentActor -down-* Stash
BasePersistentActor -down-* HasExecutionContextProvider
CoreActorExtended -up-|> CoreActor
CoreActorExtended -* HasActorTimers
CoreActor -up-|> Actor
CoreActor -* EntityIdentifier
CoreActor -down-* ActorLogging
HasActorTimers -up-|> Timers
HasTransformationRegistry -up-|> LegacyTransformationRegistry
PersistentEntityIdentifier -up-|> EntityIdentifier
AgentMsgHandler -up-|> AgentCommon
AgentMsgHandler -down-* ProtocolEngineExceptionHandler
AgentMsgHandler --* AgentIncomingMsgHandler
AgentMsgHandler --* AgentOutgoingMsgHandler
AgentMsgHandler -down-* MsgRespTimeTracker
AgentMsgHandler -* AgentStateCleanupHelper
AgentMsgHandler -down-* HasLogger
AgentCommon -up-|> AgentStateUpdateInterface
AgentCommon -* AgentIdentity
AgentCommon --* HasAgentWallet
AgentCommon -* HasSetRoute
AgentCommon --* HasMsgProgressTracker
AgentCommon --* ResourceUsageCommon
HasAgentWallet -up-|> HasWallet
HasSetRoute -up-|> HasExecutionContextProvider
HasMsgProgressTracker -up-|> HasSingletonParentProxy
AgentOutgoingMsgHandler -up-|> SendOutgoingMsg
AgentOutgoingMsgHandler -down-* AgentIdentity
AgentOutgoingMsgHandler -* HasOutgoingMsgSender
AgentOutgoingMsgHandler -down-* HasAgentActivity
HasAgentActivity -up-|> ShardRegionCommon
ShardRegionCommon -up-|> ShardRegionNames
ShardRegionNames -up-|> HasShardRegionNames
ShardRegionFromActorContext -up-|> ShardRegionCommon
AgencyAgentStateUpdateImpl -up-|> AgentStateUpdateInterface
AgencyPackedMsgHandler -up-|> ResourceUsageCommon
AgentSnapshotter --* AgentStateInterface
AgentSnapshotter -up-|> SnapshotterExt
AgentStateInterface -up-|> State
SnapshotterExt -up-|> Snapshotter
AgencyAgentPairwise -up-|> AgencyAgentCommon
AgencyAgentPairwise -* AgencyAgentPairwiseStateUpdateImpl
AgencyAgentPairwise -down-* PairwiseConnState
AgencyAgentPairwise -down-* AgentSnapshotter
AgencyAgentPairwiseStateUpdateImpl -up-|> AgentStateUpdateInterface

@enduml
