.package-common:
  stage: package
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - verity/target/docker
      - verity/target/scala-2.12/verity-assembly-*.jar
      - verity/target/*.deb
    when: always
  cache:
    paths:
      - $CI_PROJECT_DIR/.sbt/
      - $CI_PROJECT_DIR/.ivy2/
  script:
    - cd $CI_PROJECT_DIR
    - sbt assembly
    - sbt verity/k8sDockerPackage
    - sbt debian:packageBin
  tags:
    - docker-machine
    - large

package:
  extends: .package-common
  only:
    refs:
      - master@dev/verity/verity
      - main@evernym/verity/verity
      - rajesh.kalaria_ve3058_troubleshooting-changes@evernym/verity/verity

package-manual:
  extends: .package-common
  only:
    refs:
      - master
      - main
      - tags
      - merge_requests
  when: manual

.package-common-helm:
  stage: package
  image:
    name: alpine/helm:latest
    entrypoint: [""]
  tags:
    - docker-machine
    - micro
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - verity/target/helm
    when: always
  script:
    - helm package -d $CI_PROJECT_DIR/verity/target/helm $CI_PROJECT_DIR/verity/src/helm

package-helm:
  extends: .package-common-helm
  only:
    refs:
      - master@dev/verity/verity
      - main@evernym/verity/verity
    changes:
      - verity/src/helm/**/*

package-helm-manual:
  extends: .package-common-helm
  only:
    refs:
      - master
      - main
      - tags
      - merge_requests
  when: manual
