@startuml
skinparam monochrome reverse

title Outgoing Message Flow

MsgSource -> OutboxRouter:SendMsg
OutboxRouter -> RelResolverAdapter:GetRelData
...
RelResolverAdapter -> OutboxRouter:RelData
OutboxRouter -> MsgStoreAdapter: StorePayload
...
MsgStoreAdapter -> OutboxRouter: PayloadStored
OutboxRouter -> MessageMeta: AddMsgMetadata
OutboxRouter -> Outbox: AddMsg
Outbox -> Outbox: Stash
...
Outbox -> RelResolverAdapter: GetOutboxParam
...
RelResolverAdapter -> Outbox: OutboxParam
...
Outbox -> Outbox: Process AddMsg
...
Outbox -> Outbox: ProcessDeliver
Outbox -> Dispatcher: Dispatch
...
Dispatcher -> MsgSender
...
MsgSender -> Packager: PackMsg
...
Packager -> MsgSender: PackedMsg
...
MsgSender -> Transporter: SendMsg
...
Transport -> MsgSender: Response
...
MsgSender -> Outbox: RecordDeliveryAttempt

@enduml