#!/bin/bash -e

POOL_IP=$(getent hosts indy-pool | awk '{print $1}')

echo "Attempt to copy genesis file from pool to target/data/genesis.txt"
# The pool is listening on that port and will send the genesis when hit
tryCount=0
maxTries=10
mkdir -p target/
until [ $tryCount -ge $maxTries ]
do
   ((tryCount=tryCount+1))
   echo "Fetching from ${POOL_IP} port 5679 (try ${tryCount} of ${maxTries})"
   sleep 2
   curl -sf http://"${POOL_IP}":5679/genesis.txt > target/genesis.txt && break
   echo "Failed to fetch pool information"
done
