@startuml
skinparam monochrome reverse

title Outgoing Message Flow

MsgSource -> OutgoingRouter:SendMsg
OutgoingRouter -> RelResolverAdapter:SendRelData
...
RelResolverAdapter -> OutgoingRouter:RelData
OutgoingRouter -> MsgStoreAdapter: StorePayload
...
MsgStoreAdapter -> OutgoingRouter: PayloadStored
OutgoingRouter -> MessageMeta1: AddMsgMetadata
OutgoingRouter -> Outbox1: AddMsg
Outbox1 -> Outbox1: Stash
...
Outbox1 -> RelResolverAdapter: SendOutboxParam
...
RelResolverAdapter -> Outbox1: OutboxParam
...
Outbox1 -> Outbox1: Process AddMsg
...
Outbox1 -> Outbox1: ProcessPending
Outbox1 -> MsgDispatcher1: SendMsg
...
MsgDispatcher1 -> WalletAdapter: PackMsg
...
WalletAdapter -> MsgDispatcher1: PackedMsg
MsgDispatcher1 -> DeliveryAdapter: SendMsg
...
DeliveryAdapter -> MsgDispatcher1: MsgSent
MsgDispatcher1 -> Outbox1: MsgSent
...
Outbox1 -> MessageMeta1: UpdateDeliveryStatus
...
MessageMeta1 -> MsgStoreAdapter: RemovePayload

@enduml